# -*- coding: utf-8 -*-
"""gpt4o_ranking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13bvSF2XtxF372i4tn1Ji2GsJw1stlY7B
"""

import pandas as pd
import time
import json
import openai
import tempfile
import os
import math
import random

# ------------------ Set OpenAI API Key ------------------

openai.api_key = " Replace YOUR_OPENAI_API_KEY_HERE with your actual key"

# ------------------ Settings ------------------
INFERENCE_PATH = "Inference_Experiment_dataset.xlsx"
GROUND_TRUTH_PATH = "ground_truth_Evaluation.xlsx"
RANKED_OUTPUT_PATH = "gpt4o_ranked_output_shuffled.xlsx"
METRICS_OUTPUT_PATH = "gpt4o_evaluation_results_shuffled.xlsx"

MAX_CANDIDATES = 15
MODEL = "gpt-4o"
BATCH_SIZE = 5
MAX_RETRIES = 5
RETRY_WAIT = 10
HIT_K_VALUES = [3, 5, 10, 15]

# ------------------ Load Inference Data ------------------
df = pd.read_excel(INFERENCE_PATH)
commit_groups = list(df.groupby("commit_id"))

results = []

# ------------------ GPT-4o Ranking Function ------------------
def rank_candidates_gpt4o_batch(commit_batch):
    batch_prompts = []
    for commit_id, group in commit_batch:
        problem_text = group.problem_text.iloc[0]

        # Shuffle candidates to remove positional bias
        shuffled_group = group.sample(frac=1, random_state=42)
        candidate_texts = shuffled_group.solution_text.tolist()[:MAX_CANDIDATES]
        original_indices = shuffled_group.solution_index.tolist()[:MAX_CANDIDATES]

        candidate_list_text = "\n".join([f"{i+1}. {c}" for i, c in enumerate(candidate_texts)])
        prompt = f"""
You are an expert software architect.
Rank the following candidate Stack Overflow posts
according to their relevance to solve the architectural problem.

Return ONLY a comma-separated list of indices.

Problem:
{problem_text}

Candidates:
{candidate_list_text}
"""
        batch_prompts.append((commit_id, candidate_texts, original_indices, prompt))

    batch_rankings = []

    for commit_id, candidate_texts, original_indices, prompt in batch_prompts:
        for attempt in range(MAX_RETRIES):
            try:
                response = openai.chat.completions.create(
                    model=MODEL,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0,#default temperature for reporducibility
                    max_tokens=128
                )
                text = response.choices[0].message.content.strip()
                indices = [int(x.strip()) - 1 for x in text.replace("\n", " ").split(",") if x.strip().isdigit()]
                if len(indices) != len(candidate_texts):
                    print(f"Warning: GPT-4o returned incomplete ranking for {commit_id}. Using sequential fallback.")
                    indices = list(range(len(candidate_texts)))
                batch_rankings.append((commit_id, candidate_texts, original_indices, indices))
                break
            except Exception as e:
                print(f"Attempt {attempt+1} failed for {commit_id}: {e}")
                time.sleep(RETRY_WAIT)
        else:
            print(f"All retries failed for {commit_id}. Using sequential order.")
            indices = list(range(len(candidate_texts)))
            batch_rankings.append((commit_id, candidate_texts, original_indices, indices))
    return batch_rankings

# ------------------ Run Batches ------------------
num_batches = math.ceil(len(commit_groups) / BATCH_SIZE)

for b in range(num_batches):
    batch = commit_groups[b*BATCH_SIZE : (b+1)*BATCH_SIZE]
    batch_rankings = rank_candidates_gpt4o_batch(batch)
    for commit_id, candidate_texts, original_indices, ranked_indices in batch_rankings:
        for rank_position, idx in enumerate(ranked_indices, start=1):
            results.append({
                "commit_id": commit_id,
                "rank": rank_position,
                "solution_index": original_indices[idx],
                "solution_text": candidate_texts[idx]
            })
    time.sleep(0.5)

# ------------------ Save Ranked Output ------------------
ranked_df = pd.DataFrame(results)
ranked_df.to_excel(RANKED_OUTPUT_PATH, index=False)
print("GPT-4o ranking with shuffled candidates saved to:", RANKED_OUTPUT_PATH)

# ------------------ Evaluate ------------------
ground_truth_df = pd.read_excel(GROUND_TRUTH_PATH)
merged_df = ranked_df.merge(
    ground_truth_df[['commit_id', 'solution_index', 'label']],
    on=['commit_id', 'solution_index'],
    how='left'
)

metrics_list = []
for commit_id, group in merged_df.groupby("commit_id"):
    group = group.sort_values("rank")
    labels = group.label.tolist()
    metrics = {}
    for k in HIT_K_VALUES:
        metrics[f"Hit@{k}"] = int(any(labels[:k]))
    try:
        first_rel = next(i+1 for i, l in enumerate(labels) if l == 1)
        metrics["MRR"] = 1.0 / first_rel
    except StopIteration:
        metrics["MRR"] = 0.0
    metrics["commit_id"] = commit_id
    metrics_list.append(metrics)

metrics_df = pd.DataFrame(metrics_list)
metrics_df.to_excel(METRICS_OUTPUT_PATH, index=False)
overall_metrics = metrics_df[["Hit@3","Hit@5","Hit@10","Hit@15","MRR"]].mean()
print("Evaluation metrics saved to:", METRICS_OUTPUT_PATH)
print("Overall Metrics:")
print(overall_metrics)

